# `budget` resources are not yet available in crossplane - https://github.com/upbound/provider-gcp/issues/95
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: ph-tbproject-budget
spec:
  forProvider:
    source: Inline
    module: |
      data "google_project" "project" {
        project_id = var.project_id
      }

      resource "google_billing_budget" "budget" {
        billing_account = var.billing_account_id
        display_name = var.display_name
        
        budget_filter {
          projects = ["projects/${data.google_project.project.number}"]
          calendar_period = "YEAR"
        }

        amount {
          specified_amount {
            currency_code = "CAD"
            units = "2000"
          }
        }

        threshold_rules {
            threshold_percent =  0.5
            spend_basis = "CURRENT_SPEND"
        }
        threshold_rules {
            threshold_percent =  0.9
            spend_basis = "CURRENT_SPEND"
        }
        threshold_rules {
            threshold_percent =  1.0
            spend_basis = "CURRENT_SPEND"
        }

      }

      variable "billing_account_id" {
        description = "ID of the billing account to set a budget on."
        type        = string
      }

      variable "display_name" {
        description = "User data for display name in UI. Must be <= 60 chars."
        type        = string
      }

      variable "project_id" {
        description = "Usage from only this project id should be included in the budget"
        type        = string
      }

    vars:
      - key: billing_account_id
        value: 016B6D-6AB281-505940
      - key: display_name
        value: ph-tbproject-budget
      - key: project_id
        value: ph-tbproject
  providerConfigRef:
    name: terraform
