# used for autopilot cluster
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: resourceprovisioner
spec:
  deletionPolicy: Delete
  forProvider:
    displayName: resourceprovisioner 
    description: To provision resources within the project
    project: ph-tbproject
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: resourceprovisioner-storage-admin
spec:
  deletionPolicy: Delete
  forProvider:
    project: ph-tbproject
    member: "serviceAccount:resourceprovisioner@ph-tbproject.iam.gserviceaccount.com"
    role: roles/storage.admin
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: resourceprovisioner
spec:
  forProvider:
    serviceAccountIdRef:
      name: resourceprovisioner
  writeConnectionSecretToRef:
    name: resourceprovisioner
    namespace: crossplane-system
  providerConfigRef:
    name: gcp
