apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: science-platform
  namespace: flux-system
  labels:
    backstage.io/kubernetes-id: infra-core
spec:
  interval: 2m0s
  path: ./k8s/infra/SciencePlatform/gcp
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-system
