apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp
spec:
  credentials:
    secretRef:
      key: creds
      name: management-crossplane
      namespace: crossplane-system
    source: Secret
  projectID: php-01hdpgnv25h
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: terraform
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
    - filename: gcp-credentials.json
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: management-crossplane
        key: creds
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
    provider "google" {
      credentials = "gcp-credentials.json"
      project     = "php-01hdpgnv25h"
    }

    // Modules _must_ use remote state. The provider does not persist state.
    terraform {
      backend "kubernetes" {
        secret_suffix     = "tf-default"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }
