---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-system-crds
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/crossplane-system/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
  # to ensure providerconfig CRD exists before creating it's CR
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: providerconfigs.gcp.upbound.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: providerconfigs.tf.upbound.io
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-system
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/crossplane-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-system-crds
