---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-system-crds
  namespace: flux-system
  labels:
    backstage.io/kubernetes-id: infra-core
spec:
  interval: 2m0s
  path: ./k8s/crossplane-system/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-system-providers
  namespace: flux-system
  labels:
    backstage.io/kubernetes-id: infra-core
spec:
  interval: 2m0s
  path: ./k8s/crossplane-system/providers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-system-crds
  # to ensure providerconfig CRD exists before creating it's CR
  healthChecks:
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-gcp-cloudplatform
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-gcp-storage
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-gcp-dns
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-gcp-artifact
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-gcp-cloudbuild
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-gcp-compute
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-gcp-notebooks
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: upbound-terraform
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-system
  namespace: flux-system
  labels:
    backstage.io/kubernetes-id: infra-core
spec:
  interval: 2m0s
  path: ./k8s/crossplane-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-system-providers
