---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane-stable
  namespace: flux-system
spec:
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
  install:
    crds: Create
  interval: 2h0m0s
  releaseName: crossplane-stable
  targetNamespace: crossplane-system
  upgrade:
    crds: CreateReplace
  values:
    args:
      - --enable-environment-configs
    provider:
      packages:
        - xpkg.upbound.io/upbound/provider-gcp-cloudplatform:v0.38.0
        - xpkg.upbound.io/upbound/provider-gcp-storage:v0.38.0
        - xpkg.upbound.io/upbound/provider-terraform:v0.11.0
