apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- issuers.yaml
- certificate.yaml

patches:
- target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: ingress-cert
    namespace: istio-system
  patch: |-
    - op: add
      path: /spec/dnsNames/-
      value: "*.backstage.phac.alpha.canada.ca"

- target:
    group: cert-manager.io
    version: v1
    kind: ClusterIssuer
    name: letsencrypt
  patch: |-
    - op: add
      path: /spec/acme/solvers/-
      value:
        dns01:
          cloudDNS:
            project: php-01hdpgnv25h

- target:
    group: cert-manager.io
    version: v1
    kind: ClusterIssuer
    name: letsencrypt
  patch: |-
    - op: add
      path: /spec/acme/email
      value: vedant.thapa@phac-aspc.gc.ca
