apiVersion: dip.phac.gc.ca/v1beta1
kind: XVertexAI
metadata:
  name: ${{ values.name | dump }}
  labels:
    backstage.io/kubernetes-id: infra-core
spec:
  name: ${{ values.name | dump }}
  iamUser: ${{ values.iamUser | dump }}
  region: ${{ values.region | dump }}
  notebookConfig:
    idleShutdownTimeout: ${{ values.idleShutdownTimeout | dump }}
    machineType: ${{ values.machineType | dump }}
    diskType: ${{ values.diskType| dump }}
    diskSizeGb: ${{ values.diskSizeGb | dump }}
