apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: vertex-ai
  title: VertexAI + Cloud Storage 
  description: Template for the scaffolder to submit a pull-request for provisioning a VertexAI Managed Notebook and Cloud Storage bucket in a new GCP project space.
spec:
  owner: group:platform-team
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Required parameters
      required:
        - name
        - iamUser
      properties:
        name:
          title: Project Name
          type: string
          description: Name of the project
          maxLength: 30
          ui:autofocus: true
          pattern: ^[a-z0-9-]+$

        iamUser:
          title: GCP Email
          type: string
          description: GCP User to set as Owner for the project
          ui:autofocus: true
          pattern: ^[a-zA-Z0-9._%+-]+@gcp\.hc-sc\.gc\.ca$

    - title: Optional Configurations
      properties:
        region:
          title: Region
          type: string
          description: Geographic region where you want to provision resources
          default: northamerica-northeast1
          enum:
            - northamerica-northeast1
            - northamerica-northeast2
          enumNames:
            - Montréal (northamerica-northeast1)
            - Toronto (northamerica-northeast2)

        idleShutdownTimeout:
          title: Idle Shutdown Timeout
          type: integer
          description: Idle time in minutes to wait before shuting down VertexAI runtime
          ui:autofocus: true
          default: 180

        machineType:
          title: Compute instance
          type: string
          description: Compute instance type to use. See https://cloud.google.com/compute/docs/general-purpose-machines#n1-standard for valid values
          ui:autofocus: true
          default: n1-standard-1
          enum:
            - n1-standard-1
            - n1-standard-2
            - n1-standard-4
            - n1-standard-8
            - n1-standard-16
            - n1-standard-32
            - n1-standard-64
            - n1-standard-96
            - n1-highmem-2
            - n1-highmem-4
            - n1-highmem-8
            - n1-highmem-16
            - n1-highmem-32
            - n1-highmem-64
            - n1-highmem-96
          enumNames:
            - 1vCPU, 3.75GB Memory
            - 2vCPU (1 core), 7.5GB Memory
            - 4vCPU (2 core), 15GB Memory
            - 8vCPU (4 core), 30GB Memory
            - 16vCPU (8 core), 60GB Memory
            - 32vCPU (16 core), 120GB Memory
            - 64vCPU (32 core), 240GB Memory
            - 96vCPU (48 core), 360GB Memory
            - 2vCPU (1 core), 13GB Memory
            - 4vCPU (2 core), 26GB Memory
            - 8vCPU (4 core), 52GB Memory
            - 16vCPU (8 core), 104GB Memory
            - 32vCPU (16 core), 208GB Memory
            - 64vCPU (32 core), 416GB Memory
            - 96vCPU (48 core), 624GB Memory

        diskType:
          title: Disk Type
          type: string
          description: The type of the boot disk attached to this runtime. See https://cloud.google.com/compute/docs/disks/#disk-types for more info.
          ui:autofocus: true
          default: PD_STANDARD
          enum:
            - DISK_TYPE_UNSPECIFIED
            - PD_STANDARD
            - PD_SSD
            - PD_BALANCED
            - PD_EXTREME
          enumNames:
            - Disk type not set
            - Standard persistent disk type
            - SSD persistent disk type
            - Balanced persistent disk type
            - Extreme persistent disk type

        diskSizeGb:
          title: Disk Size
          type: integer
          description: Specifies the size of the disk in base-2 GB. If not specified, the disk will be the same size as the image (usually 10GB). If specified, the size must be equal to or larger than 10GB. 
          ui:autofocus: true
          default: 100
          
        description:
          title: Description
          type: string
          description: Description for the Pull Request
          ui:widget: textarea
          ui:options:
            rows: 2
          ui:autofocus: true

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        targetPath: ./content
        values:
          name: ${{ parameters.name }}
          iamUser: ${{ parameters.iamUser }}
          region: ${{ parameters.region }}
          idleShutdownTimeout: ${{ parameters.idleShutdownTimeout }}
          machineType: ${{ parameters.machineType }}
          diskType: ${{ parameters.diskType }}
          diskSizeGb: ${{ parameters.diskSizeGb }}
          description: ${{ parameters.description }}

    - id: publish-pr
      name: Publish PR in GitOps Repository
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=infra-core&owner=PHACDataHub
        branchName: xvertexai-${{ parameters.name }}
        title: '[backstage-bot] Create XVertexAI-${{ parameters.name }}'
        description: |
          ${{ parameters.description if parameters.description }}
        sourcePath: content
        targetPath: k8s/infra/SciencePlatform/gcp/
        update: true
        reviewers:
          - vedantthapa

  output:
    links:
      - title: View Pull Request on GitHub
        url: ${{ steps['publish-pr'].output.remoteUrl }}
      - title: View Kubernetes Status
        url: "https://backstage.phac.alpha.canada.ca/catalog/default/component/infra-core/kubernetes"
