apiVersion: dip.phac.gc.ca/v1beta1
kind: XVertexAI
metadata:
  name: ${{ values.name | dump }}
spec:
  name: ${{ values.name | dump }}
  iamUser: ${{ values.iamUser | dump }}
  ipCidrRange: ${{ values.ipCidrRange | dump }}
  region: ${{ values.region | dump }}
