apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gcp-controller-config.yaml
  - gcp.yaml
  - terraform.yaml

patches:
  # Using the minimum pod resources https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#compute-class-min-max
  - patch: |
      apiVersion: pkg.crossplane.io/v1
      kind: Provider
      metadata:
        name: all
      spec:
        controllerConfigRef:
          name: resource-config
    target:
      kind: Provider
      name: "(upbound-gcp-cloudplatform|upbound-gcp-storage|upbound-gcp-dns|upbound-gcp-artifact|upbound-gcp-cloudbuild|upbound-gcp-compute|upbound-gcp-notebooks)"
