apiVersion: cloudbuild.gcp.upbound.io/v1beta1
kind: Trigger
metadata:
  name: backstage-main
spec:
  deletionPolicy: Delete
  forProvider:
    filename: backstage/cloudbuild.yaml
    name: main-trigger
    description: Cloud build trigger for main branch of the repo
    location: northamerica-northeast1
    includedFiles:
      - backstage/**
    includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
    github:
      # need to manually connect repo to cloud build via console
      - name: infra-core 
        owner: PHACDataHub
        push:
          - branch: main
  providerConfigRef:
    name: gcp
