apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: dns01-solver
spec:
  deletionPolicy: Delete
  forProvider:
    displayName: dns01-solver
    description: To complete the DNS01 challenge for cert-manager
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: dns01-solver
spec:
  deletionPolicy: Delete
  forProvider:
    member: "serviceAccount:dns01-solver@php-01hdpgnv25h.iam.gserviceaccount.com"
    role: roles/dns.admin
    project: php-01hdpgnv25h
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: dns01-solver
spec:
  deletionPolicy: Delete
  forProvider:
    member: "serviceAccount:php-01hdpgnv25h.svc.id.goog[cert-manager/cert-manager]"
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: dns01-solver
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: gcr-credentials-sync
spec:
  deletionPolicy: Delete
  forProvider:
    displayName: gcr-credentials-sync
    description: To get credentials for artifact repository
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: gcr-credentials-sync
spec:
  deletionPolicy: Delete
  forProvider:
    member: "serviceAccount:gcr-credentials-sync@php-01hdpgnv25h.iam.gserviceaccount.com"
    role: roles/artifactregistry.reader
    project: php-01hdpgnv25h
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: gcr-credentials-sync
spec:
  deletionPolicy: Delete
  forProvider:
    member: "serviceAccount:php-01hdpgnv25h.svc.id.goog[flux-system/gcr-credentials-sync]"
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: gcr-credentials-sync
  providerConfigRef:
    name: gcp

---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: techdocs-object-admin
spec:
  deletionPolicy: Delete
  forProvider:
    displayName: techdocs-object-admin
    description: To get read docs from a gcp bucket
  providerConfigRef:
    name: gcp
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketIAMMember
metadata:
  name: techdocs-object-admin
spec:
  deletionPolicy: Delete
  forProvider:
    member: "serviceAccount:techdocs-object-admin@php-01hdpgnv25h.iam.gserviceaccount.com"
    role: roles/storage.objectAdmin
    bucketRef:
      name: backstage-techdocs-01hdpgnv25h
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: techdocs-object-admin
spec:
  deletionPolicy: Delete
  forProvider:
    member: "serviceAccount:php-01hdpgnv25h.svc.id.goog[backstage/backstage]"
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: techdocs-object-admin
  providerConfigRef:
    name: gcp
