apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: dns01-solver
spec:
  deletionPolicy: Delete
  forProvider:
    displayName: dns01-solver
    description: To complete the DNS01 challenge for cert-manager
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: dns01-solver
spec:
  deletionPolicy: Delete
  forProvider:
    member: "serviceAccount:dns01-solver@php-01hdpgnv25h.iam.gserviceaccount.com"
    role: roles/dns.admin
    project: php-01hdpgnv25h
  providerConfigRef:
    name: gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: dns01-solver
spec:
  deletionPolicy: Delete
  forProvider:
    member: "serviceAccount:php-01hdpgnv25h.svc.id.goog[cert-manager/cert-manager]"
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: dns01-solver
  providerConfigRef:
    name: gcp
