apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      containers:
        - name: backstage
          image: northamerica-northeast1-docker.pkg.dev/php-01hdpgnv25h/backstage/backstage:main-10d9102-1700787432 # {"$imagepolicy": "flux-system:backstage"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: google-secrets
          env:
            - name: URL
              value: 'https://backstage.phac.alpha.canada.ca'
          readinessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
          resources:
            # Autopilot only considers requests (see https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#resource-limits)
            requests:
              # using the minimum pod resources https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#compute-class-min-max
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: github-app
              mountPath: /app/secret
      volumes:
        - name: github-app
          secret:
            secretName: github-app
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  type: NodePort
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http
