apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backstage
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/backstage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-system
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: backstage
  namespace: flux-system
spec:
  image: northamerica-northeast1-docker.pkg.dev/php-01hdpgnv25h/backstage/backstage
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: backstage
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^main-[a-fA-F0-9]+-(?P<ts>.*)
  imageRepositoryRef:
    name: backstage
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: backstage
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 5m
  update:
    strategy: Setters
    path: .
  git:
    checkout:
      ref:
        branch: "main"
    commit:
      author:
        name: fluxbot
        email: fluxcd@users.noreply.github.com
      messageTemplate: "[ci skip] {{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: "main"
